### ISSUE TITLE
How to refer global objects inside worker?

### ISSUE THREAD

**Issue by caracal7** [dlevs/multiworker#2]

**Comment by dlevs** [comment]
You can use `self` in worker code to refer to the worker scope, but you won't have access to the normal global `window` object.

https://stackoverflow.com/questions/11219775/global-variable-in-web-worker

**Comment by caracal7** [comment]
I need something like this)

```
        let MyFunc = (x) => x * 5;


        let MyMultiWorker = new MultiWorker({
            worker: function () {
                self.receive = function (opts) {
                    console.log('worker started!')
                    self.return(MyFunc(opts.x));
                }
            }
        });
```
But i get **ReferenceError: Can't find variable: MyFunc**

**Comment by caracal7** [comment]
Or how to use external libraries inside the worker? For example JQuery and etc...

**Comment by dlevs** [comment]
Ah, you should be able to do something like that. Look at the "dependencies" section in the [main README](https://github.com/dlevs/multiworker). There's an example:

```javascript
var worker = new MultiWorker({
    worker: function () {
        self.receive = function (n1, n2) {
            self.return(multiply(n1, n2) + add(n1, n2));
        }
    },
    dependencies: [
        function multiply(n1, n2) {
            return n1 * n2;
        },
        function add(n1, n2) {
            return n1 + n2;
        }
    ]
});
```

It's a bit limited though. The functions have to be named and cannot reference any variables outside of themselves.

For including whole libraries, you can use do something like `importScripts('jquery-2.1.4.min.js');` in the worker, though jQuery might not work well without access to globals, and it can't access the DOM from inside the web worker. See this thread:
https://stackoverflow.com/questions/10491448/how-to-access-jquery-in-html-5-web-worker

**Comment by caracal7** [comment]
Thanks)
